format = """
[](fg:#77216F)\
[ ](bg:#77216F fg:#EB6536)\
[](bg:#EB6536 fg:#77216F)\
$directory\
[](fg:#EB6536 bg:#6E3C61)\
$git_branch\
$git_status\
[](fg:#6E3C61 bg:#5E2750)\
$nodejs\
$python\
$terraform\
$rust\
$golang\
$php\
[](fg:#5E2750)\
\n$character"""

[directory]
style = "fg:#2C001E bg:#EB6536"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#6E3C61"
format = '[[ $symbol $branch ](fg:#CECAC5 bg:#6E3C61)]($style)'

[git_status]
style = "bg:#6E3C61"
format = '[[($all_status$ahead_behind )](fg:#CECAC5 bg:#6E3C61)]($style)'

[nodejs]
symbol = ""
style = "bg:#5E2750"
format = '[[ $symbol ($version)](fg:#539e43 $style)]($style)'

[python]
symbol = " "
style = "bg:#5E2750"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#5E2750)]($style)'

[terraform]
symbol = "󱁢 "
style = "bg:#5E2750"
format = '[ $symbol[$workspace](fg:#F29879 $style) ]($style)'

[rust]
symbol = ""
style = "bg:#5E2750"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#5E2750)]($style)'

[golang]
symbol = ""
style = "bg:#5E2750"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#5E2750)]($style)'

[php]
symbol = ""
style = "bg:#5E2750"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#5E2750)]($style)'

