format = """
[](fg:#77216F)\
[ ](bg:#77216F fg:#EB6536)\
[](bg:#EB6536 fg:#77216F)\
$directory\
[](fg:#EB6536 bg:#8E6784)\
$git_branch\
$git_status\
[](fg:#8E6784 bg:#6E3C61)\
$nodejs\
$python\
$rust\
$golang\
$php\
[](fg:#6E3C61 bg:#5E2750)\
$time\
[ ](fg:#5E2750)\
\n$character"""

[directory]
style = "fg:#2C001E bg:#EB6536"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#8E6784"
format = '[[ $symbol $branch ](fg:#411934 bg:#8E6784)]($style)'

[git_status]
style = "bg:#8E6784"
format = '[[($all_status$ahead_behind )](fg:#411934 bg:#8E6784)]($style)'

[nodejs]
symbol = ""
style = "bg:#6E3C61"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#6E3C61)]($style)'

[python]
symbol = " "
style = "bg:#6E3C61"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#6E3C61)]($style)'

[rust]
symbol = ""
style = "bg:#6E3C61"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#6E3C61)]($style)'

[golang]
symbol = ""
style = "bg:#6E3C61"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#6E3C61)]($style)'

[php]
symbol = ""
style = "bg:#6E3C61"
format = '[[ $symbol ($version) ](fg:#F29879 bg:#6E3C61)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5E2750"
format = '[[  $time ](fg:#CECAC5 bg:#5E2750)]($style)'
